apiVersion: v1
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
  - name: container2
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
spec:
  containers:
  - name: container3
    image: nginx:alpine